### ISSUE TITLE
你好 ，请问 react-native v0.59.8支持吗？

### ISSUE THREAD

**Issue by Dmedu** [JonsonHI/SignWithApple#1]

**Comment by JonsonHI** [comment]
您好支持的  这就是原声的代码，只要你是iOS13设备


在2020年02月14日 23:42，Alex 写道：

**Comment by Dmedu** [comment]
> 您好支持的 这就是原声的代码，只要你是iOS13设备 | | 刘 邮箱：ljskd2@163.com | 签名由 网易邮箱大师 定制 在2020年02月14日 23:42，Alex 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢
