### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by Dmedu** [JonsonHI/SignWithApple#2]
您好，您这个包里边CoustomView类中也没用到_instance;CoustomView.m引入的SignWithAppleHelper.h文件也没有，能给我发送一份完整的代码吗？十分感谢！我的邮箱是：iszhangxz@foxmail.com

**Comment by JonsonHI** [comment]
CoustomView.m  在文件里的  
你可以直接导入 SignWithAppleHelper.h
写一个 和原生交互的方法:



RCT_EXPORT_METHOD(SignWithApple)

{

     [SignWithAppleHelpersignInWithAppleWithButtonRect:CGRectMake(100, 100, 200, 60) withSupView:[[CoustomViewalloc] init]  withType:ASAuthorizationAppleIDButtonTypeSignInwithStyle:ASAuthorizationAppleIDButtonStyleWhiteOutlinesuccess:^(ASAuthorization * _Nonnull authorization, NSString * _Nonnull user) {




       } failure:^(NSError * _Nonnull err) {




       }];

};

Js端调用就可以了





在2020年02月20日 15:05，Alex<notifications@github.com> 写道：

您好，您这个包里边CoustomView类中也没用到_instance;CoustomView.m引入的SignWithAppleHelper.h文件也没有，能给我发送一份完整的代码吗？十分感谢！我的邮箱是：iszhangxz@foxmail.com
