### ISSUE TITLE
文件拖入项目哪个文件夹下？

### ISSUE THREAD

**Issue by cnpmge** [JonsonHI/SignWithApple#3]
请问，您的文件需要拖动到哪个文件夹下？还是自己创建一个文件夹？
引用后CoustomView.m里的SignWithAppleHelper.h提示file not found
请作者帮帮忙

**Comment by JonsonHI** [comment]
都可以，自己创建一个文件夹项目会干净一些，后面我会放到pod里




| |
刘
邮箱：ljskd2@163.com
|

签名由 网易邮箱大师 定制

在2020年03月25日 13:35，cnpmge 写道：

请问，您的文件需要拖动到哪个文件夹下？还是自己创建一个文件夹？

**Comment by cnpmge** [comment]
> 都可以，自己创建一个文件夹项目会干净一些，后面我会放到pod里 | | 刘 邮箱：ljskd2@163.com | 签名由 网易邮箱大师 定制 在2020年03月25日 13:35，cnpmge 写道： 请问，您的文件需要拖动到哪个文件夹下？还是自己创建一个文件夹？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

SignWithAppleHelper.h这个提示错误是为什么啊
![1](https://user-images.githubusercontent.com/48587696/77516941-37f30c80-6eb6-11ea-86b6-7e96165a7059.jpg)
您的文件里并没有这个.h文件，我应该怎么获得并去除这个错误呢？

**Comment by JonsonHI** [comment]
有详细的错误信息吗




| |
刘
邮箱：ljskd2@163.com
|

签名由 网易邮箱大师 定制

在2020年03月25日 16:32，cnpmge 写道：

都可以，自己创建一个文件夹项目会干净一些，后面我会放到pod里 | | 刘 邮箱：ljskd2@163.com | 签名由 网易邮箱大师 定制 在2020年03月25日 13:35，cnpmge 写道： 请问，您的文件需要拖动到哪个文件夹下？还是自己创建一个文件夹？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

SignWithAppleHelper.h这个提示错误是为什么啊

**Comment by cnpmge** [comment]
有，提示SignWithAppleHelper.h file not found

**Comment by JonsonHI** [comment]
我看到这个文件你已经导入了   明天我看下项目给你回复   这种问题就是找不到头文件导致的




| |
刘
邮箱：ljskd2@163.com
|

签名由 网易邮箱大师 定制

在2020年03月25日 16:36，cnpmge 写道：

有，提示SignWithAppleHelper.h file not found

**Comment by cnpmge** [comment]
好的，麻烦您了

**Comment by JonsonHI** [comment]
> 好的，麻烦您了

你拖入项目的时候 没有 把他放到iOS 文件下   或者说 你没有选择 copy 的问题  
![image](https://user-images.githubusercontent.com/18373125/77600256-4ab32300-6f42-11ea-99b6-1789e54b8adb.png)

**Comment by cnpmge** [comment]
您好，您的图片加载不出来，可以发我邮箱吗？953340770@qq.com

**Comment by JonsonHI** [comment]
稍等  升级  MacOS  15.4




| |
刘
邮箱：ljskd2@163.com
|

签名由 网易邮箱大师 定制

在2020年03月26日 09:19，cnpmge 写道：

您好，您的图片加载不出来，可以发我邮箱吗？953340770@qq.com

**Comment by cnpmge** [comment]
![2](https://user-images.githubusercontent.com/48587696/77600942-57387b00-6f44-11ea-94bc-dd17d4838e98.jpg)
您好，我看到了您的截图了，我这里并没有SignWithAppleHelper.h这个文件，而您的截图有，是否是这个原因呢？

**Comment by JonsonHI** [comment]
> ![2](https://user-images.githubusercontent.com/48587696/77600942-57387b00-6f44-11ea-94bc-dd17d4838e98.jpg)
> 您好，我看到了您的截图了，我这里并没有SignWithAppleHelper.h这个文件，而您的截图有，是否是这个原因呢？

好了 已经上传 不好意思  是我的问题

**Comment by JonsonHI** [comment]
如果没问题的话 我就关闭这个 issue了

**Comment by cnpmge** [comment]
好的，谢谢
