### ISSUE TITLE
编译报错。

### ISSUE THREAD

**Issue by GuoJiKaiHehe** [JonsonHI/SignWithApple#5]
In file included from /Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:9:
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.h:11:41: error: no type or protocol named 'UIWindowSceneDelegate'
@interface SceneDelegate : UIResponder <UIWindowSceneDelegate>
                                        ^
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:18:16: error: expected a type
- (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions {
               ^
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:18:54: error: expected a type
- (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions {
                                                     ^
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:18:88: error: expected a type
- (void)scene:(UIScene *)scene willConnectToSession:(UISceneSession *)session options:(UISceneConnectionOptions *)connectionOptions {
                                                                                       ^
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:25:29: error: expected a type
- (void)sceneDidDisconnect:(UIScene *)scene {
                            ^
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:33:31: error: expected a type
- (void)sceneDidBecomeActive:(UIScene *)scene {
                              ^
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:39:32: error: expected a type
- (void)sceneWillResignActive:(UIScene *)scene {
                               ^
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:45:35: error: expected a type
- (void)sceneWillEnterForeground:(UIScene *)scene {
                                  ^
/Users/i/fuwuqi/react-native/liuhualive/SignWithApple/SceneDelegate.m:51:34: error: expected a type
- (void)sceneDidEnterBackground:(UIScene *)scene {

**Comment by JonsonHI** [comment]
这个文件是 iOS13后项目自带的 你可以删除的
